#!/bin/bash

branch=${1:-master}

# cd /etc/puppetlabs/code/environments/production/; /usr/bin/git fetch && /usr/bin/git reset --hard origin/${branch} && git submodule sync && git submodule update --init --recursive

/opt/puppetlabs/puppet/bin/r10k deploy environment -p

/opt/puppetlabs/bin/puppet module list --tree --environment ${branch}
/opt/puppetlabs/bin/puppet apply /etc/puppetlabs/code/environments/${branch}/manifests/site.pp --environment ${branch}

if [ $? -eq 0 ]
then
    /usr/bin/logger -i "Puppet has run successfully" -t "puppet-run"
    exit 0
else
    /usr/bin/logger -i "Puppet has ran into an error, please run Puppet manually" -t "puppet-run"
    exit 1
fi
