#!/bin/bash

branch=${1:-master}

cd /etc/puppetlabs/code/environments/production/; /usr/bin/git fetch && /usr/bin/git reset --hard origin/${branch} && git submodule sync && git submodule update --init --recursive

/opt/puppetlabs/bin/puppet module list --tree
/opt/puppetlabs/bin/puppet apply /etc/puppetlabs/code/environments/production/manifests/site.pp

if [ $? -eq 0 ]
then
    /usr/bin/logger -i "Puppet has run successfully" -t "puppet-run"
    exit 0
else
    /usr/bin/logger -i "Puppet has ran into an error, please run Puppet manually" -t "puppet-run"
    exit 1
fi
